### ISSUE TITLE
求教，运行起来报错connection refused

### ISSUE THREAD

**Issue by DoomZoe** [jw-star/pornbot_go#2]
报错信息：

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.113:443: connect: connection refused

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.113:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.113:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.113:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.113:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.113:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.113:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 216.58.200.241:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 216.58.200.241:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 216.58.200.241:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 216.58.200.241:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.81:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.81:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.113:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.43.17:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.43.17:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.43.17:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.43.17:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.43.17:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.43.17:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.43.17:443: i/o timeout

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.43.17:443: connect: connection refused

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.42.241:443: connect: connection refused

go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.24.17:443: connect: connection refused

**Comment by jw-star** [comment]
保证自己的网络是有代理的，可以设置编译器的代理，还有贴一下你的配置

**Comment by jw-star** [comment]
保证自己的网络是有代理的，可以设置编译器的代理，还有贴一下你的配置

> 报错信息：
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.113:443: connect: connection refused
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.113:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.113:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.113:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.113:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.113:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.113:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 216.58.200.241:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 216.58.200.241:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 216.58.200.241:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 216.58.200.241:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.81:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.81:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.160.113:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.43.17:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.43.17:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.43.17:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.43.17:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.43.17:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.43.17:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.43.17:443: i/o timeout
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.43.17:443: connect: connection refused
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 142.251.42.241:443: connect: connection refused
> 
> go: github.com/PuerkitoBio/goquery@v1.7.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod": dial tcp 172.217.24.17:443: connect: connection refused

保证自己的网络是有代理的，可以设置编译器的代理，还有贴一下你的配置
