### ISSUE TITLE
怎么破解的ip限制呀?

### ISSUE THREAD

**Issue by kevinmay99** [jw-star/pornbot_go#3]
每次下15个就不行了，能否提供一下思路?

**Comment by jw-star** [comment]
> 每次下15个就不行了，能否提供一下思路?

你是在哪里测试的

**Comment by jw-star** [comment]
> 每次下15个就不行了，能否提供一下思路?

请求头生成随机ip就可以 X-Forwarded-For

**Comment by kevinmay99** [comment]
好像确实可以，我页面加了，详情页没加。。自己写的python
