### ISSUE TITLE
添加nginx反代出现问题

### ISSUE THREAD

**Issue by shanghaojia-1** [jw-star/pornbot_go#4]
在conf.yml中填写的端口为443，docker将8090端口映射到pornbot的443端口，在nginx反向代理处转发给127.0.0.1:8090，无法正常运行，nginx已开启ssl。
![image](https://user-images.githubusercontent.com/13851271/146662892-ef09bc64-2a00-4944-b815-d77c4d5a6690.png)

**Comment by jw-star** [comment]
私聊我吧  qq邮箱对应的qq
