### ISSUE TITLE
大佬，按教程启动后，发送/hello无反应

### ISSUE THREAD

**Issue by beer-on-ice** [jw-star/pornbot_go#5]
三个镜像都跑起来了，也没报错，日志到这后，tgbot没反应,也没新的日志
`
Creating redis       ... done
Creating telegramApi ... done
Creating pornbot     ... done
Attaching to redis, pornbot, telegramApi
redis               | 1:C 20 Dec 2021 06:39:02.529 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis               | 1:C 20 Dec 2021 06:39:02.529 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis               | 1:C 20 Dec 2021 06:39:02.529 # Configuration loaded
redis               | 1:M 20 Dec 2021 06:39:02.530 * monotonic clock: POSIX clock_gettime
redis               | 1:M 20 Dec 2021 06:39:02.532 * Running mode=standalone, port=6379.
redis               | 1:M 20 Dec 2021 06:39:02.532 # Server initialized
redis               | 1:M 20 Dec 2021 06:39:02.532 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis               | 1:M 20 Dec 2021 06:39:02.532 * Ready to accept connections
telegramApi         | telegram-bot-api --http-port 8081 --dir=/var/lib/telegram-bot-api --temp-dir=/tmp/telegram-bot-api --username=telegram-bot-api --groupname=telegram-bot-api
pornbot             | 2021/12/20 14:39:03 读取配置文件
pornbot             | 2021/12/20 14:39:03 &{token https://域名 :8443 4 [] -1001537953026 0 29 8 * * ? 127.0.0.1:16379 3321 2 23 http://域名:8081 true :8082}
pornbot             | 2021/12/20 14:39:03 初始化redis连接...
pornbot             | 2021/12/20 14:39:03 Dict files path:  [/home/dictionary.txt]
pornbot             | 2021/12/20 14:39:03 Load the gse dictionary: "/home/dictionary.txt"
pornbot             | 2021/12/20 14:39:09 Gse dictionary loaded finished.
pornbot             | 2021/12/20 14:39:09 Load the stop word dictionary: "/home/stop_word.txt"
pornbot             | 2021/12/20 14:39:09 Dict files path:  [/config/word.txt]
pornbot             | 2021/12/20 14:39:09 Load the gse dictionary: "/config/word.txt"
pornbot             | 2021/12/20 14:39:12 Gse dictionary loaded finished.
pornbot             | 2021/12/20 14:39:12 定时任务开启

`

**Comment by jw-star** [comment]
麻烦贴下你的配置，conf.yml,docker-compose.yml

**Comment by beer-on-ice** [comment]
conf.yml
-------------------- 
`listen_port: ":8082"
#telegram  Token
token: "Token"
#webhook地址，即nginx对应的地址
webhook_url: "https://域名"
webhook_port: ":8443"
max_connections: 4
#定时任务开关
cron_switch: true
#首页定时任务爬取时间
spec: "0 29 8 * * ?"

redis_address: "127.0.0.1:16379"
redis_pass: 3321

#本地telegram 客户端地址
local_api: "http://域名:8081"
#定时任务发到哪个群里
telegram_id: -100151111111
threads: 2
crf: 23`

docker-compose.yml
----------------------------
`version: "3.7"

services:
  # telegram本地服务,请提前申请好对应的apiId和hash
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest        
    container_name: telegramApi
    environment:
      TELEGRAM_API_ID: "id"
      TELEGRAM_API_HASH: "hash"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api    
    ports:
      - 8081:8081

  # bot业务
  pornbot:
    image: jwstar/pornbot_tg
    container_name: pornbot
    restart: always
    volumes:
      - /root/porn:/config
    ports:
      - "8082:8082"
    # init处理僵尸进程，防止chrome进程没有被关闭
    init: true
    deploy:
      resources:
        limits:
          cpus: '0.80'

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: redis-server --requirepass 3321 --appendonly yes
    ports:
      - "16379:6379"
    volumes:
      - ./data:/data

volumes:
  telegram-bot-api-data:`

**Comment by jw-star** [comment]
加我邮箱对应的qq吧，配置看上去没问题

**Comment by beer-on-ice** [comment]
加了大佬

**Comment by jw-star** [comment]
> 加了大佬

2419254437,你加错了？

**Comment by beer-on-ice** [comment]
没有错，又加了一次

**Comment by beer-on-ice** [comment]
大佬，我再贴下我的caddy反代
`
:8443 {
 gzip
 proxy / http://ip:8082
 tls ssh@ik.me
}
`

**Comment by jw-star** [comment]
> 大佬，我再贴下我的caddy反代 `:8443 { gzip proxy / http://ip:8082 tls ssh@ik.me }`

发你的qq，我加吧

**Comment by beer-on-ice** [comment]
997477295

**Comment by jw-star** [comment]
加了
